version: '3.3'

services:
  # db-server:
  #   image: mysqldb:latest
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #   volumes:
  #       - ./db-server/init.sql:/docker-entrypoint-initdb.d/custom-init.sql
  #   ports:
  #     - '3306:3306'
  server:
    build: .
    ports:
      - '80:80'
    environment:
      - FLASK_ENV=Development